# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tagger_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tagger_message.proto',
  package='tagger_message',
  syntax='proto2',
  serialized_pb=_b('\n\x14tagger_message.proto\x12\x0etagger_message\"W\n\tTagResult\x12\x14\n\x0c\x64ocumentName\x18\x01 \x02(\t\x12\x0f\n\x07success\x18\x02 \x02(\x08\x12\x11\n\ttagResult\x18\x04 \x01(\x04\x12\x10\n\x08resultID\x18\x03 \x02(\x04\"<\n\x0f\x44ocumentFeature\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\"E\n\x10\x44ocumentFeatures\x12\x31\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x1f.tagger_message.DocumentFeature\"k\n\nTagRequest\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x14\n\x0c\x64ocumentName\x18\x02 \x01(\t\x12:\n\x10\x64ocumentFeatures\x18\x03 \x01(\x0b\x32 .tagger_message.DocumentFeatures')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAGRESULT = _descriptor.Descriptor(
  name='TagResult',
  full_name='tagger_message.TagResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentName', full_name='tagger_message.TagResult.documentName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='tagger_message.TagResult.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagResult', full_name='tagger_message.TagResult.tagResult', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultID', full_name='tagger_message.TagResult.resultID', index=3,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=127,
)


_DOCUMENTFEATURE = _descriptor.Descriptor(
  name='DocumentFeature',
  full_name='tagger_message.DocumentFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tagger_message.DocumentFeature.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tagger_message.DocumentFeature.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tagger_message.DocumentFeature.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=189,
)


_DOCUMENTFEATURES = _descriptor.Descriptor(
  name='DocumentFeatures',
  full_name='tagger_message.DocumentFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='tagger_message.DocumentFeatures.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=260,
)


_TAGREQUEST = _descriptor.Descriptor(
  name='TagRequest',
  full_name='tagger_message.TagRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='tagger_message.TagRequest.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentName', full_name='tagger_message.TagRequest.documentName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentFeatures', full_name='tagger_message.TagRequest.documentFeatures', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=369,
)

_DOCUMENTFEATURES.fields_by_name['features'].message_type = _DOCUMENTFEATURE
_TAGREQUEST.fields_by_name['documentFeatures'].message_type = _DOCUMENTFEATURES
DESCRIPTOR.message_types_by_name['TagResult'] = _TAGRESULT
DESCRIPTOR.message_types_by_name['DocumentFeature'] = _DOCUMENTFEATURE
DESCRIPTOR.message_types_by_name['DocumentFeatures'] = _DOCUMENTFEATURES
DESCRIPTOR.message_types_by_name['TagRequest'] = _TAGREQUEST

TagResult = _reflection.GeneratedProtocolMessageType('TagResult', (_message.Message,), dict(
  DESCRIPTOR = _TAGRESULT,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.TagResult)
  ))
_sym_db.RegisterMessage(TagResult)

DocumentFeature = _reflection.GeneratedProtocolMessageType('DocumentFeature', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTFEATURE,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.DocumentFeature)
  ))
_sym_db.RegisterMessage(DocumentFeature)

DocumentFeatures = _reflection.GeneratedProtocolMessageType('DocumentFeatures', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTFEATURES,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.DocumentFeatures)
  ))
_sym_db.RegisterMessage(DocumentFeatures)

TagRequest = _reflection.GeneratedProtocolMessageType('TagRequest', (_message.Message,), dict(
  DESCRIPTOR = _TAGREQUEST,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.TagRequest)
  ))
_sym_db.RegisterMessage(TagRequest)


# @@protoc_insertion_point(module_scope)
