# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tagger_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tagger_message.proto',
  package='tagger_message',
  syntax='proto2',
  serialized_pb=_b('\n\x14tagger_message.proto\x12\x0etagger_message\"\x7f\n\tTagResult\x12\x14\n\x0c\x64ocumentName\x18\x01 \x02(\t\x12\x0f\n\x07success\x18\x02 \x02(\x08\x12\x0c\n\x04type\x18\x05 \x02(\t\x12\r\n\x05\x63lass\x18\x08 \x01(\x04\x12\x10\n\x08resultID\x18\x03 \x02(\x04\x12\x0c\n\x04keys\x18\x06 \x03(\t\x12\x0e\n\x06values\x18\x07 \x03(\t\"<\n\x0f\x44ocumentFeature\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\r\n\x05value\x18\x03 \x02(\t\"\xd5\x01\n\nTagRequest\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x14\n\x0c\x64ocumentName\x18\x02 \x01(\t\x12J\n\x10\x64ocumentFeatures\x18\x03 \x03(\x0b\x32\x30.tagger_message.TagRequest.DocumentFeaturesEntry\x1aX\n\x15\x44ocumentFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.tagger_message.DocumentFeature:\x02\x38\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TAGRESULT = _descriptor.Descriptor(
  name='TagResult',
  full_name='tagger_message.TagResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='documentName', full_name='tagger_message.TagResult.documentName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='tagger_message.TagResult.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tagger_message.TagResult.type', index=2,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class', full_name='tagger_message.TagResult.class', index=3,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resultID', full_name='tagger_message.TagResult.resultID', index=4,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keys', full_name='tagger_message.TagResult.keys', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='tagger_message.TagResult.values', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=167,
)


_DOCUMENTFEATURE = _descriptor.Descriptor(
  name='DocumentFeature',
  full_name='tagger_message.DocumentFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tagger_message.DocumentFeature.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='tagger_message.DocumentFeature.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tagger_message.DocumentFeature.value', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=229,
)


_TAGREQUEST_DOCUMENTFEATURESENTRY = _descriptor.Descriptor(
  name='DocumentFeaturesEntry',
  full_name='tagger_message.TagRequest.DocumentFeaturesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tagger_message.TagRequest.DocumentFeaturesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='tagger_message.TagRequest.DocumentFeaturesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=445,
)

_TAGREQUEST = _descriptor.Descriptor(
  name='TagRequest',
  full_name='tagger_message.TagRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='tagger_message.TagRequest.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentName', full_name='tagger_message.TagRequest.documentName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentFeatures', full_name='tagger_message.TagRequest.documentFeatures', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TAGREQUEST_DOCUMENTFEATURESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=445,
)

_TAGREQUEST_DOCUMENTFEATURESENTRY.fields_by_name['value'].message_type = _DOCUMENTFEATURE
_TAGREQUEST_DOCUMENTFEATURESENTRY.containing_type = _TAGREQUEST
_TAGREQUEST.fields_by_name['documentFeatures'].message_type = _TAGREQUEST_DOCUMENTFEATURESENTRY
DESCRIPTOR.message_types_by_name['TagResult'] = _TAGRESULT
DESCRIPTOR.message_types_by_name['DocumentFeature'] = _DOCUMENTFEATURE
DESCRIPTOR.message_types_by_name['TagRequest'] = _TAGREQUEST

TagResult = _reflection.GeneratedProtocolMessageType('TagResult', (_message.Message,), dict(
  DESCRIPTOR = _TAGRESULT,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.TagResult)
  ))
_sym_db.RegisterMessage(TagResult)

DocumentFeature = _reflection.GeneratedProtocolMessageType('DocumentFeature', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENTFEATURE,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.DocumentFeature)
  ))
_sym_db.RegisterMessage(DocumentFeature)

TagRequest = _reflection.GeneratedProtocolMessageType('TagRequest', (_message.Message,), dict(

  DocumentFeaturesEntry = _reflection.GeneratedProtocolMessageType('DocumentFeaturesEntry', (_message.Message,), dict(
    DESCRIPTOR = _TAGREQUEST_DOCUMENTFEATURESENTRY,
    __module__ = 'tagger_message_pb2'
    # @@protoc_insertion_point(class_scope:tagger_message.TagRequest.DocumentFeaturesEntry)
    ))
  ,
  DESCRIPTOR = _TAGREQUEST,
  __module__ = 'tagger_message_pb2'
  # @@protoc_insertion_point(class_scope:tagger_message.TagRequest)
  ))
_sym_db.RegisterMessage(TagRequest)
_sym_db.RegisterMessage(TagRequest.DocumentFeaturesEntry)


_TAGREQUEST_DOCUMENTFEATURESENTRY.has_options = True
_TAGREQUEST_DOCUMENTFEATURESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
